package io.tornado.optimization;
import io.tornado.persistence.*;
import java.time.*;
import java.util.*;

/** Pure chronological selector. The final 20% test block is never used by candidate ranking. */
public class WalkForwardProfileSelector{
 public List<CandidateEvaluation>rank(Map<Configuration,List<Observation>>candidateData,int minimumSamples,double roundTripCostPercent){return candidateData.entrySet().stream().map(e->evaluate(e.getKey(),e.getValue(),minimumSamples,roundTripCostPercent)).sorted(Comparator.comparing(CandidateEvaluation::eligible).reversed().thenComparing(Comparator.comparingDouble(CandidateEvaluation::selectionScore).reversed()).thenComparing(Comparator.comparingLong((CandidateEvaluation x)->x.evidence().validationSamples()).reversed())).toList();}
 CandidateEvaluation evaluate(Configuration configuration,List<Observation>input,int minimum,double cost){List<Observation>all=input.stream().sorted(Comparator.comparing(Observation::signalAt)).toList();int testStart=(int)Math.floor(all.size()*.8),trainEnd=(int)Math.floor(all.size()*.4);List<Observation>train=all.subList(0,Math.min(trainEnd,all.size())),validation=all.subList(Math.min(trainEnd,all.size()),Math.min(testStart,all.size())),test=all.subList(Math.min(testStart,all.size()),all.size());int minimumTest=Math.max(20,minimum/2);boolean eligible=train.size()>=minimum&&validation.size()>=minimum&&test.size()>=minimumTest;Metrics validationMetrics=metrics(validation,cost);List<List<Observation>>windows=windows(validation,4);long positive=windows.stream().filter(w->{Metrics m=metrics(w,cost);return m.netPnlPercent>0&&m.directionalAccuracy>=50;}).count();double consistency=windows.isEmpty()?0:positive*100.0/windows.size();double profitNormalized=Math.max(-1,Math.min(1,validationMetrics.averageNetReturn/.30));double drawdownPenalty=Math.min(1,validationMetrics.maximumDrawdownPercent/5.0);double score=100*(.35*validationMetrics.wilsonDirectional/100+.25*validationMetrics.wilsonTarget/100+.15*validationMetrics.wilsonProfitable/100+.15*((profitNormalized+1)/2)+.10*(consistency/100)-.10*drawdownPenalty);Metrics testMetrics=metrics(test,cost);StrategyHorizonProfile.Evidence evidence=new StrategyHorizonProfile.Evidence(train.size(),validation.size(),test.size(),testMetrics.targetHitRate,testMetrics.directionalAccuracy,testMetrics.wilsonTarget,testMetrics.wilsonDirectional,testMetrics.profitableRate,testMetrics.averageAlignedReturn,testMetrics.medianAlignedReturn,testMetrics.netPnlPercent,testMetrics.maximumDrawdownPercent,windows.size(),(int)positive,consistency,eligible?score:0);Instant validationFrom=validation.isEmpty()?null:validation.getFirst().signalAt(),testFrom=test.isEmpty()?null:test.getFirst().signalAt();return new CandidateEvaluation(configuration,evidence,eligible,eligible?score:Double.NEGATIVE_INFINITY,validationFrom,testFrom);}
 private List<List<Observation>>windows(List<Observation>rows,int desired){if(rows.isEmpty())return List.of();int size=Math.max(1,(int)Math.ceil(rows.size()/(double)desired));List<List<Observation>>out=new ArrayList<>();for(int start=0;start<rows.size();start+=size)out.add(rows.subList(start,Math.min(rows.size(),start+size)));return out;}
 private Metrics metrics(List<Observation>rows,double cost){if(rows.isEmpty())return new Metrics();List<Double>aligned=new ArrayList<>(),net=new ArrayList<>();long target=0,directional=0,profitable=0;for(Observation o:rows){double raw=o.exitPrice().subtract(o.entryPrice()).divide(o.entryPrice(),12,java.math.RoundingMode.HALF_UP).doubleValue()*100,edge=o.direction()==Direction.UP?raw:-raw,n=edge-cost;aligned.add(edge);net.add(n);if(edge>=.30)target++;if(edge>0)directional++;if(n>0)profitable++;}double cumulative=0,peak=0,drawdown=0;for(double n:net){cumulative+=n;peak=Math.max(peak,cumulative);drawdown=Math.max(drawdown,peak-cumulative);}List<Double>sorted=new ArrayList<>(aligned);Collections.sort(sorted);double median=sorted.size()%2==1?sorted.get(sorted.size()/2):(sorted.get(sorted.size()/2-1)+sorted.get(sorted.size()/2))/2;return new Metrics(rows.size(),target*100.0/rows.size(),directional*100.0/rows.size(),profitable*100.0/rows.size(),wilson(target,rows.size())*100,wilson(directional,rows.size())*100,wilson(profitable,rows.size())*100,aligned.stream().mapToDouble(Double::doubleValue).average().orElse(0),median,net.stream().mapToDouble(Double::doubleValue).average().orElse(0),net.stream().mapToDouble(Double::doubleValue).sum(),drawdown);}
 public static double wilson(long successes,long total){if(total==0)return 0;double z=1.96,p=(double)successes/total,z2=z*z;return(p+z2/(2*total)-z*Math.sqrt((p*(1-p)+z2/(4*total))/total))/(1+z2/total);}
 public record Configuration(String timeframe,String parameterKey){}
 public record Observation(long coinId,Instant signalAt,Instant executionAt,Instant targetAt,Direction direction,java.math.BigDecimal entryPrice,java.math.BigDecimal exitPrice,Instant entryObservedAt,Instant exitObservedAt,long entryDelayMilliseconds,long exitDelayMilliseconds){public Observation(long coinId,Instant signalAt,Instant executionAt,Instant targetAt,Direction direction,java.math.BigDecimal entryPrice,java.math.BigDecimal exitPrice){this(coinId,signalAt,executionAt,targetAt,direction,entryPrice,exitPrice,executionAt,targetAt,0,0);}public Observation{if(signalAt.isAfter(executionAt))throw new IllegalArgumentException("Signal candle closes after execution");if(!executionAt.isBefore(targetAt))throw new IllegalArgumentException("Prediction target must follow execution");if(entryObservedAt.isBefore(executionAt)||exitObservedAt.isBefore(targetAt))throw new IllegalArgumentException("Historical trades precede their requested timestamps");if(entryDelayMilliseconds!=Duration.between(executionAt,entryObservedAt).toMillis()||exitDelayMilliseconds!=Duration.between(targetAt,exitObservedAt).toMillis())throw new IllegalArgumentException("Historical trade delay metadata is inconsistent");}}
 public record CandidateEvaluation(Configuration configuration,StrategyHorizonProfile.Evidence evidence,boolean eligible,double selectionScore,Instant validationFrom,Instant testFrom){}
 private static class Metrics{long samples;double targetHitRate,directionalAccuracy,profitableRate,wilsonTarget,wilsonDirectional,wilsonProfitable,averageAlignedReturn,medianAlignedReturn,averageNetReturn,netPnlPercent,maximumDrawdownPercent;Metrics(){}Metrics(long a,double b,double c,double d,double e,double f,double g,double h,double i,double j,double k,double l){samples=a;targetHitRate=b;directionalAccuracy=c;profitableRate=d;wilsonTarget=e;wilsonDirectional=f;wilsonProfitable=g;averageAlignedReturn=h;medianAlignedReturn=i;averageNetReturn=j;netPnlPercent=k;maximumDrawdownPercent=l;}}
}
