package io.tornado.notification;
import io.tornado.persistence.*;import org.springframework.stereotype.Component;import java.math.*;import java.time.*;import java.time.format.*;import java.util.*;
@Component public class TelegramMessageFormatter{
 private static final ZoneId TEHRAN=ZoneId.of("Asia/Tehran");private static final DateTimeFormatter TIME=DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss 'Tehran'");private static final List<String>NUMBERS=List.of("1️⃣","2️⃣","3️⃣");
 private String price(BigDecimal p){return p==null?"legacy / unavailable":String.format(Locale.US,"%,.4f",p);}private String pct(BigDecimal p){return p==null?"?":p.stripTrailingZeros().toPlainString();}private String horizon(long s){return s<3600?s/60+"m":s<86400?s/3600+"h":"24h";}
 public String open(MixTradeSimulation s){return render(s,List.of());}public String update(MixTradeSimulation s,List<MixTradeSimulation.Milestone>events){return render(s,events);}public String closed(MixTradeSimulation s){return render(s,List.of());}
 private String render(MixTradeSimulation s,List<MixTradeSimulation.Milestone>events){String side=s.getDirection()==Direction.UP?"🟢 Direction: LONG":"🔴 Direction: SHORT",banner=banner(events),status=s.getStatus()==MixTradeSimulation.Status.OPEN?"⏳ OPEN":s.getStatus()==MixTradeSimulation.Status.TP3_HIT?"🏆🎯 TP3 HIT":s.getStatus()==MixTradeSimulation.Status.SL3_HIT?"🛑❌ SL3 HIT":s.getStatus().name();return banner+"🚨 TORNIDO MIX SIGNAL\n\n🪙 Coin: "+s.getCoin().getSymbol()+"/USDT\n"+side+"\n⏱ Horizon: "+horizon(s.getHorizonSeconds())+"\n\n🏆 Mix Rank: #"+s.getMixRank()+"\n🧠 Methods:\n"+String.join(" + ",s.getMethodNames())+"\n\n🗳 Agreement: "+s.getAgreementCount()+" / "+s.getTotalMethods()+" "+(s.getDirection()==Direction.UP?"LONG":"SHORT")+"\n\n💰 Entry:\n"+price(s.getEntryPrice())+" USDT\n\n🎯 TAKE PROFITS\n\n"+line(1,"TP",s.getTp1Price(),s.getTp1Percent(),s.getTp1HitAt())+line(2,"TP",s.getTp2Price(),s.getTp2Percent(),s.getTp2HitAt())+line(3,"TP",s.getTp3Price(),s.getTp3Percent(),s.getTp3HitAt())+"\n🛑 STOP LOSSES\n\n"+line(1,"SL",s.getSl1Price(),s.getSl1Percent(),s.getSl1HitAt())+line(2,"SL",s.getSl2Price(),s.getSl2Percent(),s.getSl2HitAt())+line(3,"SL",s.getSl3Price(),s.getSl3Percent(),s.getSl3HitAt())+"\n📊 Historical Samples: "+s.getHistoricalSamples()+"\n🎯 Selected historical hit metric: TP1 (+"+pct(s.getTp1Percent())+"%) endpoint hit\n✅ Historical TP1 Hit Rate: "+String.format("%.1f%%",s.getHistoricalTargetHitRate())+"\n📈 Directional Accuracy: "+String.format("%.1f%%",s.getHistoricalDirectionalAccuracy())+"\n📐 Wilson Score: "+String.format("%.1f%%",s.getHistoricalWilsonScore())+"\n\n🕒 Opened: "+TIME.format(s.getOpenedAt().atZone(TEHRAN))+"\n📌 Simulation ID: #"+s.getId()+"\n\nStatus: "+status+(s.getResultPercent()==null?"":"\nResult: "+String.format("%+.3f%%",s.getResultPercent()));}
 private String banner(List<MixTradeSimulation.Milestone>events){if(events.isEmpty())return "";return events.stream().map(x->(x.name().startsWith("TP")?"✅ ":"❌ ")+x.name()+" TOUCHED").collect(java.util.stream.Collectors.joining(" · "))+"\n\n";}
 private String line(int number,String kind,BigDecimal price,BigDecimal percent,Instant hit){String state=hit==null?"⬜":kind.equals("TP")?"✅":"❌";return state+" "+NUMBERS.get(number-1)+" "+kind+number+": "+price(price)+" ("+(kind.equals("TP")?"+":"-")+pct(percent)+"%)"+(hit==null?"":" — HIT at "+TIME.format(hit.atZone(TEHRAN)))+"\n";}
}
