package io.tornado.persistence;
import jakarta.persistence.*;import java.math.*;import java.time.*;import java.util.*;
@Entity @Table(name="mix_trade_simulations")public class MixTradeSimulation{
 public enum Status{OPEN,TARGET_HIT,STOP_LOSS_HIT,CANCELLED,ERROR}
 @Id@GeneratedValue(strategy=GenerationType.IDENTITY)private Long id;
 @ManyToOne(fetch=FetchType.LAZY,optional=false)@JoinColumn(name="coin_id")private Coin coin;
 @ManyToOne(fetch=FetchType.LAZY)@JoinColumn(name="best_mix_id")private BestMethodMix bestMix;
 private long horizonSeconds;private int mixSize;private int mixRank;@Column(length=2000)private String methodNames;@Column(length=1000)private String strategyCodes;@Enumerated(EnumType.STRING)@Column(length=8)private Direction direction;private int agreementCount;private int totalMethods;private long historicalSamples;private double historicalTargetHitRate;private double historicalDirectionalAccuracy;private double historicalWilsonScore;private Instant openedAt;@Column(precision=30,scale=12)private BigDecimal entryPrice;@Column(precision=30,scale=12)private BigDecimal targetPrice;@Column(precision=30,scale=12)private BigDecimal stopLossPrice;@Enumerated(EnumType.STRING)@Column(length=24)private Status status;private Instant closedAt;@Column(precision=30,scale=12)private BigDecimal closePrice;@Column(precision=30,scale=12)private BigDecimal lastCheckedPrice;@Column(nullable=false)private Instant lastCheckedAt;private Double resultPercent;private Long telegramMessageId;@Column(unique=true,length=300)private String activeKey;private Instant createdAt;private Instant updatedAt;
 protected MixTradeSimulation(){}public MixTradeSimulation(Coin coin,BestMethodMix mix,Direction direction,int agreement,BigDecimal entry,BigDecimal stopPercent,Instant opened){this.coin=coin;bestMix=mix;horizonSeconds=mix.getHorizonSeconds();mixSize=mix.getMixSize();mixRank=mix.getRank();methodNames=String.join("||",mix.getMethodNames());strategyCodes=String.join("||",mix.getStrategyCodes());this.direction=direction;agreementCount=agreement;totalMethods=mixSize;historicalSamples=mix.getSamples();historicalTargetHitRate=mix.getTargetHitRate();historicalDirectionalAccuracy=mix.getDirectionalAccuracy();historicalWilsonScore=mix.getWilsonScore();openedAt=opened;entryPrice=entry;BigDecimal target=new BigDecimal("0.003"),stop=stopPercent.movePointLeft(2);targetPrice=entry.multiply(BigDecimal.ONE.add(direction==Direction.UP?target:target.negate())).setScale(12,RoundingMode.HALF_UP);stopLossPrice=entry.multiply(BigDecimal.ONE.add(direction==Direction.UP?stop.negate():stop)).setScale(12,RoundingMode.HALF_UP);status=Status.OPEN;lastCheckedPrice=entry;lastCheckedAt=opened;activeKey=activeKey(coin,mix,direction);createdAt=opened;updatedAt=opened;}
 public static String activeKey(Coin coin,BestMethodMix mix,Direction direction){StringBuilder key=new StringBuilder().append(coin.getId()).append(':').append(mix.getHorizonSeconds()).append(':');List<String>codes=mix.getStrategyCodes();List<Integer>versions=mix.getStrategyVersions();for(int i=0;i<codes.size();i++){if(i>0)key.append(',');key.append(codes.get(i)).append('@').append(versions.get(i));}return key.append(':').append(direction).toString();}
 public void telegramMessage(Long id){telegramMessageId=id;updatedAt=Instant.now();}public boolean observe(BigDecimal price,Instant at){if(status!=Status.OPEN||at.isBefore(lastCheckedAt))return false;lastCheckedPrice=price;lastCheckedAt=at;updatedAt=at;boolean target=direction==Direction.UP?price.compareTo(targetPrice)>=0:price.compareTo(targetPrice)<=0,stop=direction==Direction.UP?price.compareTo(stopLossPrice)<=0:price.compareTo(stopLossPrice)>=0;if(!target&&!stop)return false;status=target?Status.TARGET_HIT:Status.STOP_LOSS_HIT;closedAt=at;closePrice=price;resultPercent=price.subtract(entryPrice).divide(entryPrice,12,RoundingMode.HALF_UP).doubleValue()*100*(direction==Direction.UP?1:-1);activeKey=null;return true;}
 public Long getId(){return id;}public Coin getCoin(){return coin;}public BestMethodMix getBestMix(){return bestMix;}public long getHorizonSeconds(){return horizonSeconds;}public int getMixSize(){return mixSize;}public int getMixRank(){return mixRank;}public List<String>getMethodNames(){return split(methodNames);}public List<String>getStrategyCodes(){return split(strategyCodes);}public Direction getDirection(){return direction;}public int getAgreementCount(){return agreementCount;}public int getTotalMethods(){return totalMethods;}public long getHistoricalSamples(){return historicalSamples;}public double getHistoricalTargetHitRate(){return historicalTargetHitRate;}public double getHistoricalDirectionalAccuracy(){return historicalDirectionalAccuracy;}public double getHistoricalWilsonScore(){return historicalWilsonScore;}public Instant getOpenedAt(){return openedAt;}public BigDecimal getEntryPrice(){return entryPrice;}public BigDecimal getTargetPrice(){return targetPrice;}public BigDecimal getStopLossPrice(){return stopLossPrice;}public Status getStatus(){return status;}public Instant getClosedAt(){return closedAt;}public BigDecimal getClosePrice(){return closePrice;}public BigDecimal getLastCheckedPrice(){return lastCheckedPrice;}public Instant getLastCheckedAt(){return lastCheckedAt;}public Double getResultPercent(){return resultPercent;}public Long getTelegramMessageId(){return telegramMessageId;}public Instant getCreatedAt(){return createdAt;}public Instant getUpdatedAt(){return updatedAt;}private List<String>split(String s){return Arrays.asList(s.split("\\|\\|",-1));}
}
