package io.tornado.reporting;
import io.tornado.api.ReportService;import io.tornado.persistence.*;import io.tornado.persistence.PredictionRepository.ReportRow;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.*;import java.util.*;import java.util.function.LongConsumer;
@Service public class BestMixService{
 private static final BigDecimal TARGET=new BigDecimal("0.003");private final PredictionRepository predictions;private final BestMethodMixRepository mixes;private final CoinRepository coins;private final AppSettingsRepository settings;
 public BestMixService(PredictionRepository p,BestMethodMixRepository m,CoinRepository c,AppSettingsRepository s){predictions=p;mixes=m;coins=c;settings=s;}
 @Transactional public synchronized void refresh(long coinId,long horizon){ReportService.requireSupportedHorizon(horizon);Coin coin=coins.findById(coinId).orElseThrow();int minimum=settings.findById(1).orElseThrow().getMinimumMixSimulationTrades();List<ReportRow>rows=predictions.findGradedReportRows(coinId,horizon);List<Candidate>ranked=calculate(rows,minimum);mixes.deleteSlice(coinId,horizon,3);mixes.flush();List<BestMethodMix>save=new ArrayList<>();for(int size=2;size<=8;size++){int selectedSize=size,rank=0;for(Candidate c:ranked.stream().filter(x->x.size==selectedSize).limit(3).toList())save.add(new BestMethodMix(coin,horizon,size,++rank,c.codes,c.versions,c.names,c.samples,c.hits,c.directional,c.wilson));}mixes.saveAll(save);}
 @Transactional public synchronized void refresh(Collection<Slice> slices){for(Slice s:slices)refresh(s.coinId,s.horizon);}
 @Transactional public synchronized void rebuildAll(){for(Coin coin:coins.findAllByActiveTrueOrderBySymbol())for(long horizon:List.of(60L,900L,1800L,3600L,14400L,43200L,86400L))refresh(coin.getId(),horizon);}
 List<Candidate>calculate(List<ReportRow>rows,int minimum){List<Identity>identities=rows.stream().map(r->new Identity(r.getStrategyCode(),r.getStrategyVersion(),r.getMethodName())).distinct().sorted(Comparator.comparing(Identity::code).thenComparingInt(Identity::version)).toList();if(identities.size()>63)throw new IllegalStateException("at most 63 strategy versions are supported");Map<String,Integer>index=new HashMap<>();for(int i=0;i<identities.size();i++)index.put(identities.get(i).key(),i);Map<GroupKey,Group>groups=new HashMap<>();for(ReportRow r:rows)if(r.getRunId()!=null)groups.computeIfAbsent(new GroupKey(r.getRunId(),r.getCoinId()),x->new Group(r)).put(index.get(new Identity(r.getStrategyCode(),r.getStrategyVersion(),r.getMethodName()).key()),r.getPredictedDirection());Map<Integer,Map<Long,Score>>scores=new HashMap<>();for(int size=2;size<=8;size++)scores.put(size,new HashMap<>());for(Group g:groups.values())for(int size=2;size<=8;size++)if(Long.bitCount(g.methods)>=size){int n=size;combinations(g.methods,size,0,m->{int ups=Long.bitCount(m&g.ups),downs=n-ups;if(ups==downs)return;boolean up=ups>downs;Score s=scores.get(n).computeIfAbsent(m,x->new Score());s.samples++;if(g.target(up))s.hits++;if(g.direction(up))s.directional++;});}List<Candidate>out=new ArrayList<>();scores.forEach((size,map)->map.forEach((mask,s)->{if(s.samples>=minimum){List<Identity>ids=decode(mask,identities);out.add(new Candidate(size,ids.stream().map(Identity::code).toList(),ids.stream().map(Identity::version).toList(),ids.stream().map(Identity::name).toList(),s.samples,s.hits,s.directional,wilson(s.hits,s.samples)));}}));out.sort(Comparator.comparingInt((Candidate c)->c.size).thenComparing(Comparator.comparingDouble((Candidate c)->c.wilson).reversed()).thenComparing(Comparator.comparingLong((Candidate c)->c.samples).reversed()));return out;}
 private void combinations(long remaining,int needed,long selected,LongConsumer c){if(needed==0){c.accept(selected);return;}while(Long.bitCount(remaining)>=needed){long bit=Long.lowestOneBit(remaining);remaining^=bit;combinations(remaining,needed-1,selected|bit,c);}}private List<Identity>decode(long mask,List<Identity>all){List<Identity>r=new ArrayList<>();while(mask!=0){long bit=Long.lowestOneBit(mask);r.add(all.get(Long.numberOfTrailingZeros(bit)));mask^=bit;}return r;}private double wilson(long hit,long n){double z=1.96,p=(double)hit/n,z2=z*z;return(p+z2/(2*n)-z*Math.sqrt((p*(1-p)+z2/(4*n))/n))/(1+z2/n);}
 public record Slice(long coinId,long horizon){}record Identity(String code,int version,String name){String key(){return code+"\u0000"+version;}}record GroupKey(long run,long coin){}static class Score{long samples,hits,directional;}static class Group{long methods,ups;BigDecimal entry,exit;Group(ReportRow r){entry=r.getPriceAtPrediction();exit=r.getPriceAtGrading();}void put(int i,Direction d){long b=1L<<i;methods|=b;if(d==Direction.UP)ups|=b;}boolean target(boolean up){BigDecimal change=exit.subtract(entry).divide(entry,12,RoundingMode.HALF_UP);return up?change.compareTo(TARGET)>=0:change.compareTo(TARGET.negate())<=0;}boolean direction(boolean up){int c=exit.compareTo(entry);return up?c>0:c<0;}}record Candidate(int size,List<String>codes,List<Integer>versions,List<String>names,long samples,long hits,long directional,double wilson){}
}
