package io.tornado.reporting;

import io.tornado.notification.TelegramNotificationService;
import io.tornado.persistence.*;
import org.slf4j.*;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.time.*;
import java.time.format.*;
import java.util.*;

@Service
public class DailyTelegramReportService {
    public static final ZoneId TEHRAN=ZoneId.of("Asia/Tehran");
    private static final Logger log=LoggerFactory.getLogger(DailyTelegramReportService.class);
    private final MixTradeSimulationRepository simulations;private final TelegramDailyReportRepository reports;private final AppSettingsRepository settings;private final TelegramNotificationService telegram;private final Clock clock;
    @org.springframework.beans.factory.annotation.Autowired public DailyTelegramReportService(MixTradeSimulationRepository s,TelegramDailyReportRepository r,AppSettingsRepository a,TelegramNotificationService t){this(s,r,a,t,Clock.systemUTC());}
    DailyTelegramReportService(MixTradeSimulationRepository s,TelegramDailyReportRepository r,AppSettingsRepository a,TelegramNotificationService t,Clock c){simulations=s;reports=r;settings=a;telegram=t;clock=c;}
    @Transactional public synchronized void sendPreviousDay(){send(LocalDate.now(clock.withZone(TEHRAN)).minusDays(1));}
    @Transactional public void send(LocalDate date){if(!settings.findById(1).orElseThrow().isTelegramDailyReportEnabled()||!telegram.configured())return;TelegramDailyReport report=reports.findByReportDate(date).orElseGet(()->create(date));if(report.getStatus()==TelegramDailyReport.Status.SENT||report.getAttempts()>=3)return;var result=telegram.send(format(summarize(date)));if(result.status()==TelegramNotificationService.DeliveryResult.Status.SENT)report.sent(result.messageId());else report.failed(result.detail());}
    private TelegramDailyReport create(LocalDate date){Instant start=date.atStartOfDay(TEHRAN).toInstant(),end=date.plusDays(1).atStartOfDay(TEHRAN).toInstant();try{return reports.saveAndFlush(new TelegramDailyReport(date,start,end,clock.instant()));}catch(DataIntegrityViolationException e){return reports.findByReportDate(date).orElseThrow();}}
    @Transactional public synchronized void retryFailed(){for(TelegramDailyReport r:reports.findByStatusAndAttemptsLessThanOrderByReportDateAsc(TelegramDailyReport.Status.FAILED,3))try{send(r.getReportDate());}catch(Exception e){log.warn("Daily Telegram retry failed for {}: {}",r.getReportDate(),e.getMessage());}}

    public Summary summarize(LocalDate date){
        Instant start=date.atStartOfDay(TEHRAN).toInstant(),end=date.plusDays(1).atStartOfDay(TEHRAN).toInstant();
        List<MixTradeSimulation> created=simulations.findByOpenedAtGreaterThanEqualAndOpenedAtLessThan(start,end),closed=simulations.findByClosedAtGreaterThanEqualAndClosedAtLessThan(start,end);
        long targets=closed.stream().filter(this::targetClosed).count(),stops=closed.stream().filter(this::stopClosed).count(),pending=created.stream().filter(x->x.getClosedAt()==null||!x.getClosedAt().isBefore(end)).count(),longs=created.stream().filter(x->x.getDirection()==Direction.UP).count();
        double pnl=closed.stream().map(MixTradeSimulation::getResultPercent).filter(Objects::nonNull).mapToDouble(Double::doubleValue).sum();
        Map<String,MethodStat> methods=new HashMap<>();for(MixTradeSimulation s:created)for(String method:s.getMethodNames())methods.computeIfAbsent(method,MethodStat::new).add(s,end);
        Map<String,MixStat> mixes=new HashMap<>();for(MixTradeSimulation s:created)mixes.computeIfAbsent(s.getCoin().getSymbol()+"|"+s.getHorizonSeconds()+"|"+String.join(" + ",s.getMethodNames()),x->new MixStat(s)).add(s,end);
        List<LevelStat> tp=List.of(level(created,1,true,end),level(created,2,true,end),level(created,3,true,end)),sl=List.of(level(created,1,false,end),level(created,2,false,end),level(created,3,false,end));
        return new Summary(date,created.size(),targets,stops,pending,simulations.countByStatus(MixTradeSimulation.Status.OPEN),longs,created.size()-longs,pnl,tp,sl,methods.values().stream().sorted(Comparator.comparingLong(MethodStat::executions).reversed()).toList(),mixes.values().stream().sorted(Comparator.comparingLong(MixStat::executions).reversed()).toList());
    }
    private LevelStat level(List<MixTradeSimulation> rows,int number,boolean takeProfit,Instant cutoff){Set<BigDecimal> configured=new TreeSet<>();long eligible=0,reached=0;for(MixTradeSimulation s:rows){BigDecimal percent=takeProfit?tpPercent(s,number):slPercent(s,number);if(percent==null)continue;eligible++;configured.add(percent.stripTrailingZeros());Instant hit=takeProfit?tpHit(s,number):slHit(s,number);if(hit!=null&&hit.isBefore(cutoff))reached++;}String label=configured.isEmpty()?"legacy / unavailable":configured.size()==1?configured.iterator().next().toPlainString()+"%":"varied per signal";return new LevelStat(number,label,eligible,reached,eligible==0?0:reached*100.0/eligible);}
    private BigDecimal tpPercent(MixTradeSimulation s,int n){return n==1?s.getTp1Percent():n==2?s.getTp2Percent():s.getTp3Percent();}private BigDecimal slPercent(MixTradeSimulation s,int n){return n==1?s.getSl1Percent():n==2?s.getSl2Percent():s.getSl3Percent();}private Instant tpHit(MixTradeSimulation s,int n){return n==1?s.getTp1HitAt():n==2?s.getTp2HitAt():s.getTp3HitAt();}private Instant slHit(MixTradeSimulation s,int n){return n==1?s.getSl1HitAt():n==2?s.getSl2HitAt():s.getSl3HitAt();}
    private boolean targetClosed(MixTradeSimulation s){return s.getStatus()==MixTradeSimulation.Status.TP3_HIT||s.getStatus()==MixTradeSimulation.Status.TARGET_HIT;}private boolean stopClosed(MixTradeSimulation s){return s.getStatus()==MixTradeSimulation.Status.SL3_HIT||s.getStatus()==MixTradeSimulation.Status.STOP_LOSS_HIT;}

    public String format(Summary s){StringBuilder b=new StringBuilder("📊 TORNIDO DAILY REPORT\n📅 ").append(s.date.format(DateTimeFormatter.ofPattern("dd MMM uuuu",Locale.ENGLISH))).append("\n🕛 Tehran Time\n\n🚀 Signals Created: ").append(s.created).append("\n✅ TP3 Closures: ").append(s.targets).append("\n❌ SL3 Closures: ").append(s.stops).append("\n⏳ New Signals Still Open: ").append(s.pending).append("\n📌 Total Currently Open: ").append(s.totalOpen);long closed=s.targets+s.stops;b.append("\n\n🎯 Terminal Hit Rate: ").append(closed==0?"—":String.format("%d / %d = %.1f%%",s.targets,closed,s.targets*100.0/closed)).append("\n🟢 LONG Signals: ").append(s.longs).append("\n🔴 SHORT Signals: ").append(s.shorts).append("\n💵 Net Simulation P&L: ").append(String.format("%+.3f%%",s.netPnl)).append("\n\n🎯 TP MILESTONES");for(LevelStat x:s.tpMilestones)b.append("\n").append(x.level).append("️⃣ TP").append(x.level).append(" (+").append(x.percentLabel).append("): ").append(x.reached).append(" / ").append(x.eligible).append(" · ").append(String.format("%.1f%%",x.rate));b.append("\n\n🛑 SL MILESTONES");for(LevelStat x:s.slMilestones)b.append("\n").append(x.level).append("️⃣ SL").append(x.level).append(" (-").append(x.percentLabel).append("): ").append(x.reached).append(" / ").append(x.eligible).append(" · ").append(String.format("%.1f%%",x.rate));b.append("\n\n🧠 METHOD PERFORMANCE");int i=0;for(MethodStat m:s.methods){if(i++>=10)break;b.append("\n\n").append(i<=3?List.of("🥇","🥈","🥉").get(i-1):"•").append(" ").append(m.name).append("\n🚀 Executed: ").append(m.executions).append(" | ✅ ").append(m.targets).append(" | ❌ ").append(m.stops).append(" | ⏳ ").append(m.pending).append("\n🎯 Terminal Hit Rate: ").append(m.closed()==0?"—":String.format("%.1f%%",m.targets*100.0/m.closed()));}List<MixStat> eligible=s.mixes.stream().filter(x->x.closed()>=3).toList();b.append("\n\n🏆 MIX PERFORMANCE\n");if(eligible.isEmpty())b.append("Not enough closed simulations for reliable daily ranking.");else{appendMix(b,"Best",eligible.stream().max(Comparator.comparingDouble(MixStat::rate)).orElseThrow());appendMix(b,"Worst",eligible.stream().min(Comparator.comparingDouble(MixStat::rate)).orElseThrow());appendMix(b,"Most Executed",s.mixes.getFirst());}return b.toString();}
    private void appendMix(StringBuilder b,String title,MixStat m){b.append("\n\n").append(title).append(": ").append(m.methods).append("\n🪙 ").append(m.coin).append(" · ⏱ ").append(m.horizon).append("s · 🚀 ").append(m.executions).append(" · ✅ ").append(m.targets).append(" · ❌ ").append(m.stops).append(" · ⏳ ").append(m.pending).append(" · 🎯 ").append(m.closed()==0?"—":String.format("%.1f%%",m.rate()));}

    public record LevelStat(int level,String percentLabel,long eligible,long reached,double rate){}
    public record Summary(LocalDate date,long created,long targets,long stops,long pending,long totalOpen,long longs,long shorts,double netPnl,List<LevelStat>tpMilestones,List<LevelStat>slMilestones,List<MethodStat>methods,List<MixStat>mixes){}
    public static class MethodStat{final String name;long executions,targets,stops,pending,longs,shorts;MethodStat(String n){name=n;}void add(MixTradeSimulation s,Instant cutoff){executions++;if(s.getDirection()==Direction.UP)longs++;else shorts++;if(s.getClosedAt()==null||!s.getClosedAt().isBefore(cutoff))pending++;else if(s.getStatus()==MixTradeSimulation.Status.TP3_HIT||s.getStatus()==MixTradeSimulation.Status.TARGET_HIT)targets++;else if(s.getStatus()==MixTradeSimulation.Status.SL3_HIT||s.getStatus()==MixTradeSimulation.Status.STOP_LOSS_HIT)stops++;}public String name(){return name;}public long executions(){return executions;}public long targets(){return targets;}public long stops(){return stops;}public long pending(){return pending;}public long longs(){return longs;}public long shorts(){return shorts;}long closed(){return targets+stops;}}
    public static class MixStat{final String coin,methods;final long horizon;long executions,targets,stops,pending;MixStat(MixTradeSimulation s){coin=s.getCoin().getSymbol();methods=String.join(" + ",s.getMethodNames());horizon=s.getHorizonSeconds();}void add(MixTradeSimulation s,Instant cutoff){executions++;if(s.getClosedAt()==null||!s.getClosedAt().isBefore(cutoff))pending++;else if(s.getStatus()==MixTradeSimulation.Status.TP3_HIT||s.getStatus()==MixTradeSimulation.Status.TARGET_HIT)targets++;else if(s.getStatus()==MixTradeSimulation.Status.SL3_HIT||s.getStatus()==MixTradeSimulation.Status.STOP_LOSS_HIT)stops++;}public long executions(){return executions;}long closed(){return targets+stops;}double rate(){return closed()==0?0:targets*100.0/closed();}}
}
