package io.tornado.reporting;
import io.tornado.datafetch.BinanceMarketDataClient;import io.tornado.notification.*;import io.tornado.persistence.*;import org.slf4j.*;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.*;import java.math.*;import java.time.*;import java.util.*;
@Service public class MixTradeSimulationService{
 private static final Logger log=LoggerFactory.getLogger(MixTradeSimulationService.class);private final BestMethodMixRepository mixes;private final MixTradeSimulationRepository simulations;private final AppSettingsRepository settings;private final TelegramNotificationService telegram;private final TelegramMessageFormatter messages;private final BinanceMarketDataClient market;
 public MixTradeSimulationService(BestMethodMixRepository m,MixTradeSimulationRepository s,AppSettingsRepository a,TelegramNotificationService t,TelegramMessageFormatter f,BinanceMarketDataClient market){mixes=m;simulations=s;settings=a;telegram=t;messages=f;this.market=market;}
 @Transactional(propagation=Propagation.REQUIRES_NEW)public void detect(Coin coin,List<Prediction> current,Instant openedAt,BigDecimal entry){AppSettings configuration=settings.findById(1).orElseThrow();BigDecimal stop=configuration.getMixTradeStopLossPercent();Map<Long,Map<String,Direction>>byHorizon=new HashMap<>();for(Prediction p:current)byHorizon.computeIfAbsent(p.getHorizonSeconds(),x->new HashMap<>()).put(p.getStrategyCode(),p.getPredictedDirection());for(var slice:byHorizon.entrySet())for(BestMethodMix mix:mixes.findByCoinIdAndHorizonSecondsAndSignalVersionOrderByMixSizeAscRankAsc(coin.getId(),slice.getKey(),3)){List<Direction>votes=mix.getStrategyCodes().stream().map(slice.getValue()::get).filter(Objects::nonNull).toList();MixConsensus.Result consensus=MixConsensus.decide(mix.getMixSize(),votes);if(!consensus.decisive())continue;Direction direction=consensus.direction();String key=MixTradeSimulation.activeKey(coin,mix,direction);if(simulations.existsByActiveKey(key))continue;MixTradeSimulation simulation=simulations.saveAndFlush(new MixTradeSimulation(coin,mix,direction,consensus.agreement(),entry,stop,openedAt));if(configuration.isTelegramNotificationsEnabled()){var delivery=telegram.send(messages.open(simulation));if(delivery.status()==TelegramNotificationService.DeliveryResult.Status.SENT)simulation.telegramMessage(delivery.messageId());}}
 }
 @Transactional(propagation=Propagation.REQUIRES_NEW)public void observe(String pair,BigDecimal price,Instant at){for(MixTradeSimulation simulation:simulations.lockOpenByPair(pair))if(simulation.observe(price,at))notifyClosed(simulation);}
 @Transactional(propagation=Propagation.REQUIRES_NEW)public void recover(String pair,Instant through){List<MixTradeSimulation>open=simulations.lockOpenByPair(pair);if(open.isEmpty())return;Instant earliest=open.stream().map(MixTradeSimulation::getLastCheckedAt).min(Instant::compareTo).orElse(through);if(through.isBefore(earliest))return;List<BinanceMarketDataClient.AggregateTrade>trades=market.historicalTrades(pair,earliest,through);for(MixTradeSimulation simulation:open)for(var trade:trades){if(!trade.observedAt().isAfter(simulation.getLastCheckedAt()))continue;if(simulation.observe(trade.price(),trade.observedAt())){notifyClosed(simulation);break;}}}
 private void notifyClosed(MixTradeSimulation simulation){if(simulation.getTelegramMessageId()==null)return;var result=telegram.edit(simulation.getTelegramMessageId(),messages.closed(simulation));if(result.status()==TelegramNotificationService.DeliveryResult.Status.FAILED)telegram.send(messages.closed(simulation));}
 public List<MixTradeSimulation>list(MixTradeSimulation.Status status){return status==null?simulations.findTop500ByOrderByOpenedAtDesc():simulations.findTop500ByStatusOrderByOpenedAtDesc(status);}public MixTradeSimulation get(long id){return simulations.findWithCoinById(id).orElseThrow();}
}
