package io.tornado.persistence;
import org.junit.jupiter.api.Test;import org.springframework.test.util.ReflectionTestUtils;import java.math.*;import java.time.*;import java.util.*;import static org.assertj.core.api.Assertions.assertThat;
class MixTradeSimulationTest{private final Instant now=Instant.parse("2026-08-14T10:00:00Z");
 @Test void oneJumpMarksEveryTakeProfitAndClosesOnlyAtTp3(){var s=simulation(Direction.UP);var event=s.observeMilestones(new BigDecimal("101"),now.plusSeconds(1));assertThat(event.milestones()).containsExactly(MixTradeSimulation.Milestone.TP1,MixTradeSimulation.Milestone.TP2,MixTradeSimulation.Milestone.TP3);assertThat(s.getStatus()).isEqualTo(MixTradeSimulation.Status.TP3_HIT);assertThat(s.observe(new BigDecimal("90"),now.plusSeconds(2))).isFalse();}
 @Test void intermediateLevelsAreIdempotentAndDoNotClose(){var s=simulation(Direction.UP);Instant hit=now.plusSeconds(1);assertThat(s.observeMilestones(new BigDecimal("100.5"),hit).milestones()).containsExactly(MixTradeSimulation.Milestone.TP1,MixTradeSimulation.Milestone.TP2);assertThat(s.getStatus()).isEqualTo(MixTradeSimulation.Status.OPEN);assertThat(s.getTradeOutcome()).isEqualTo(MixTradeSimulation.TradeOutcome.SUCCESS);assertThat(s.getSuccessAt()).isEqualTo(hit);assertThat(s.observeMilestones(new BigDecimal("100.5"),now.plusSeconds(2)).changed()).isFalse();}
 @Test void shortStopUsesInclusiveThresholdAndMarksAllLevels(){var s=simulation(Direction.DOWN);var event=s.observeMilestones(new BigDecimal("101"),now.plusSeconds(1));assertThat(event.milestones()).containsExactly(MixTradeSimulation.Milestone.SL1,MixTradeSimulation.Milestone.SL2,MixTradeSimulation.Milestone.SL3);assertThat(s.getStatus()).isEqualTo(MixTradeSimulation.Status.SL3_HIT);}
 @Test void sl1FirstPermanentlyMarksTradeFailedEvenIfTp1IsTouchedLater(){var s=simulation(Direction.UP);Instant failed=now.plusSeconds(1);s.observeMilestones(new BigDecimal("99.7"),failed,10L);s.observeMilestones(new BigDecimal("100.6"),now.plusSeconds(2),11L);assertThat(s.getTradeOutcome()).isEqualTo(MixTradeSimulation.TradeOutcome.FAILED);assertThat(s.getFailureAt()).isEqualTo(failed);assertThat(s.getSuccessAt()).isNull();assertThat(s.getTp1HitAt()).isNotNull();}
 @Test void tp1FirstPermanentlyMarksTradeSuccessfulEvenIfAllStopsAreTouchedLater(){var s=simulation(Direction.UP);Instant success=now.plusSeconds(1);s.observeMilestones(new BigDecimal("100.3"),success,10L);s.observeMilestones(new BigDecimal("99"),now.plusSeconds(2),11L);assertThat(s.getTradeOutcome()).isEqualTo(MixTradeSimulation.TradeOutcome.SUCCESS);assertThat(s.getSuccessAt()).isEqualTo(success);assertThat(s.getFailureAt()).isNull();assertThat(s.getSl3HitAt()).isNotNull();}
 @Test void qualifyingOpportunityDoesNotLockLaterSnapshots(){Coin c=coin();var s=new MixTradeSimulation(c,mix(c),Direction.UP,2,new BigDecimal("100"),TpSlLevels.defaults(),now);assertThat(s.getActiveKey()).isNull();}
 @Test void recordsAggregateTradeSequenceForEqualTimestampMilestones(){var s=simulation(Direction.UP);s.observeMilestones(new BigDecimal("99.7"),now.plusSeconds(1),100L);s.observeMilestones(new BigDecimal("100.6"),now.plusSeconds(1),101L);assertThat(s.slHitSequence(1)).isEqualTo(100L);assertThat(s.tpHitSequence(2)).isEqualTo(101L);}
 @Test void duplicateAggregateTradeDoesNotDuplicateMilestones(){var s=simulation(Direction.UP);s.observeMilestones(new BigDecimal("100.3"),now.plusSeconds(1),10L);assertThat(s.getTp1HitAt()).isEqualTo(now.plusSeconds(1));assertThat(s.observeMilestones(new BigDecimal("100.3"),now.plusSeconds(1),10L).changed()).isFalse();assertThat(s.observeMilestones(new BigDecimal("100.3"),now.plusSeconds(1),9L).changed()).isFalse();assertThat(s.observeMilestones(new BigDecimal("100.3"),now.plusSeconds(1),11L).changed()).isFalse();assertThat(s.observeMilestones(new BigDecimal("100.5"),now.plusSeconds(2),12L).changed()).isTrue();assertThat(s.tpHitAt(2)).isEqualTo(now.plusSeconds(2));}
 @Test void suppressedOpportunityHasNoActiveKeyButStillTracksMilestones(){Coin c=coin();var s=new MixTradeSimulation(c,mix(c),Direction.UP,2,new BigDecimal("100"),TpSlLevels.defaults(),now,new BigDecimal("70"),false,"WIN_RATE_BELOW_THRESHOLD");assertThat(s.getActiveKey()).isNull();assertThat(s.observeMilestones(new BigDecimal("100.5"),now.plusSeconds(1),10L).milestones()).contains(MixTradeSimulation.Milestone.TP1,MixTradeSimulation.Milestone.TP2);}
 private MixTradeSimulation simulation(Direction d){Coin c=coin();return new MixTradeSimulation(c,mix(c),d,2,new BigDecimal("100"),TpSlLevels.defaults(),now);}private Coin coin(){Coin c=new Coin("BTC","BTCUSDT");ReflectionTestUtils.setField(c,"id",1L);return c;}private BestMethodMix mix(Coin c){return new BestMethodMix(c,900,2,1,List.of("A","B"),List.of(1,1),List.of("A","B"),50,30,35,.52);}
}
