ALTER TABLE app_settings ADD COLUMN minimum_configuration_samples INTEGER NOT NULL DEFAULT 100;
ALTER TABLE app_settings ADD COLUMN profile_replacement_minimum_improvement_percent NUMERIC(8,4) NOT NULL DEFAULT 2.0000;
ALTER TABLE app_settings ADD COLUMN coin_profile_minimum_samples INTEGER NOT NULL DEFAULT 250;
ALTER TABLE app_settings ADD COLUMN profile_research_round_trip_cost_percent NUMERIC(8,4) NOT NULL DEFAULT 0.1000;
ALTER TABLE app_settings ADD COLUMN profile_refresh_interval_hours INTEGER NOT NULL DEFAULT 24;
ALTER TABLE app_settings ADD COLUMN automatic_profile_research_enabled BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE best_method_mixes DROP CONSTRAINT uk_best_mix_slice_rank;
ALTER TABLE best_method_mixes ADD CONSTRAINT uk_best_mix_slice_rank_version UNIQUE(coin_id,horizon_seconds,mix_size,rank_number,signal_version);

CREATE TABLE strategy_horizon_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  strategy_code VARCHAR(80) NOT NULL,
  strategy_version INTEGER NOT NULL,
  prediction_horizon_seconds BIGINT NOT NULL,
  analysis_timeframe VARCHAR(10) NOT NULL,
  parameter_key VARCHAR(120) NOT NULL,
  profile_version INTEGER NOT NULL,
  profile_scope VARCHAR(20) NOT NULL,
  coin_id BIGINT REFERENCES coins(id),
  selection_source VARCHAR(32) NOT NULL,
  training_samples BIGINT NOT NULL DEFAULT 0,
  validation_samples BIGINT NOT NULL DEFAULT 0,
  test_samples BIGINT NOT NULL DEFAULT 0,
  target_hit_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
  directional_accuracy DOUBLE PRECISION NOT NULL DEFAULT 0,
  wilson_target_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  wilson_directional_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  profitable_trade_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
  average_market_return DOUBLE PRECISION NOT NULL DEFAULT 0,
  median_market_return DOUBLE PRECISION NOT NULL DEFAULT 0,
  net_pnl_percent DOUBLE PRECISION NOT NULL DEFAULT 0,
  maximum_drawdown_percent DOUBLE PRECISION NOT NULL DEFAULT 0,
  walk_forward_windows INTEGER NOT NULL DEFAULT 0,
  walk_forward_positive_windows INTEGER NOT NULL DEFAULT 0,
  walk_forward_consistency DOUBLE PRECISION NOT NULL DEFAULT 0,
  selection_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  active_key VARCHAR(220) UNIQUE,
  selected_at TIMESTAMP WITH TIME ZONE NOT NULL,
  superseded_at TIMESTAMP WITH TIME ZONE,
  replacement_reason VARCHAR(500),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT uk_strategy_profile_version UNIQUE(profile_scope,coin_id,strategy_code,strategy_version,prediction_horizon_seconds,profile_version)
);
CREATE INDEX idx_strategy_profiles_active ON strategy_horizon_profiles(active,prediction_horizon_seconds,strategy_code);
CREATE INDEX idx_strategy_profiles_coin ON strategy_horizon_profiles(coin_id,active,prediction_horizon_seconds);

ALTER TABLE predictions ADD COLUMN strategy_horizon_profile_id BIGINT REFERENCES strategy_horizon_profiles(id);
CREATE INDEX idx_predictions_profile ON predictions(strategy_horizon_profile_id);
CREATE INDEX idx_predictions_v3_slice ON predictions(signal_version,coin_id,horizon_seconds,outcome,predicted_at);
