DELETE FROM best_method_mixes
WHERE id IN (
  SELECT id FROM (
    SELECT id, ROW_NUMBER() OVER (
      PARTITION BY coin_id, horizon_seconds, signal_version, tp_level
      ORDER BY wilson_score DESC, samples DESC, target_hit_rate DESC,
               directional_accuracy DESC, mix_size ASC, id ASC
    ) AS duplicate_rank
    FROM best_method_mixes
  ) ranked
  WHERE duplicate_rank > 1
);

ALTER TABLE best_method_mixes DROP CONSTRAINT uk_best_mix_slice_rank_version_tp;
ALTER TABLE best_method_mixes ADD CONSTRAINT uk_best_mix_slice_version_tp
  UNIQUE (coin_id, horizon_seconds, signal_version, tp_level);

CREATE TABLE active_signal_locks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coin_id BIGINT NOT NULL REFERENCES coins(id),
  horizon_seconds BIGINT NOT NULL,
  best_method_mix_id BIGINT REFERENCES best_method_mixes(id) ON DELETE SET NULL,
  mix_trade_simulation_id BIGINT NOT NULL UNIQUE REFERENCES mix_trade_simulations(id),
  opened_at TIMESTAMP WITH TIME ZONE NOT NULL,
  entry_price NUMERIC(30,12) NOT NULL,
  expected_close_at TIMESTAMP WITH TIME ZONE NOT NULL,
  status VARCHAR(24) NOT NULL,
  closed_at TIMESTAMP WITH TIME ZONE,
  close_price NUMERIC(30,12),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_active_signal_lock_status ON active_signal_locks(status);
CREATE INDEX idx_active_signal_lock_due ON active_signal_locks(status, expected_close_at);
CREATE INDEX idx_active_signal_lock_simulation ON active_signal_locks(mix_trade_simulation_id);
