CREATE TABLE coins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol VARCHAR(20) NOT NULL UNIQUE,
  pair VARCHAR(30) NOT NULL UNIQUE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE predictions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coin_id BIGINT NOT NULL REFERENCES coins(id),
  method_name VARCHAR(100) NOT NULL,
  predicted_at TIMESTAMP WITH TIME ZONE NOT NULL,
  predicted_direction VARCHAR(10) NOT NULL,
  price_at_prediction NUMERIC(30,12) NOT NULL,
  horizon_seconds BIGINT NOT NULL,
  price_at_grading NUMERIC(30,12),
  outcome VARCHAR(12) NOT NULL DEFAULT 'PENDING',
  graded_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_prediction_due ON predictions(outcome, predicted_at);
CREATE INDEX idx_prediction_filters ON predictions(coin_id, method_name, predicted_at);

CREATE TABLE app_settings (
  id INTEGER PRIMARY KEY,
  snapshot_interval_seconds BIGINT NOT NULL,
  grading_horizon_seconds BIGINT NOT NULL
);
