CREATE TABLE analysis_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  horizon_seconds BIGINT NOT NULL,
  status VARCHAR(20) NOT NULL,
  completed_at TIMESTAMP WITH TIME ZONE,
  error_count INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE predictions ADD COLUMN analysis_run_id BIGINT REFERENCES analysis_runs(id);
CREATE INDEX idx_predictions_run ON predictions(analysis_run_id);
UPDATE app_settings SET grading_horizon_seconds = 900;
