-- Telegram secrets are environment-owned. Remove the transitional database columns.
ALTER TABLE app_settings DROP COLUMN telegram_bot_token;
ALTER TABLE app_settings DROP COLUMN telegram_chat_id;
ALTER TABLE app_settings ADD COLUMN minimum_mix_simulation_trades INTEGER NOT NULL DEFAULT 30;
ALTER TABLE app_settings ADD COLUMN mix_trade_stop_loss_percent NUMERIC(8,4) NOT NULL DEFAULT 0.5000;
ALTER TABLE app_settings ADD COLUMN telegram_daily_report_enabled BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE best_method_mixes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coin_id BIGINT NOT NULL REFERENCES coins(id),
  horizon_seconds BIGINT NOT NULL,
  mix_size INTEGER NOT NULL,
  rank_number INTEGER NOT NULL,
  strategy_codes VARCHAR(1000) NOT NULL,
  strategy_versions VARCHAR(500) NOT NULL,
  method_names VARCHAR(2000) NOT NULL,
  samples BIGINT NOT NULL,
  target_hits BIGINT NOT NULL,
  target_hit_rate DOUBLE PRECISION NOT NULL,
  directional_correct BIGINT NOT NULL,
  directional_accuracy DOUBLE PRECISION NOT NULL,
  wilson_score DOUBLE PRECISION NOT NULL,
  ranking_score DOUBLE PRECISION NOT NULL,
  signal_version INTEGER NOT NULL,
  calculated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT uk_best_mix_slice_rank UNIQUE(coin_id,horizon_seconds,mix_size,rank_number)
);
CREATE INDEX idx_best_mix_slice ON best_method_mixes(coin_id,horizon_seconds,mix_size);

CREATE TABLE mix_trade_simulations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coin_id BIGINT NOT NULL REFERENCES coins(id),
  best_mix_id BIGINT REFERENCES best_method_mixes(id) ON DELETE SET NULL,
  horizon_seconds BIGINT NOT NULL,
  mix_size INTEGER NOT NULL,
  mix_rank INTEGER NOT NULL,
  method_names VARCHAR(2000) NOT NULL,
  strategy_codes VARCHAR(1000) NOT NULL,
  direction VARCHAR(8) NOT NULL,
  agreement_count INTEGER NOT NULL,
  total_methods INTEGER NOT NULL,
  historical_samples BIGINT NOT NULL,
  historical_target_hit_rate DOUBLE PRECISION NOT NULL,
  historical_directional_accuracy DOUBLE PRECISION NOT NULL,
  historical_wilson_score DOUBLE PRECISION NOT NULL,
  opened_at TIMESTAMP WITH TIME ZONE NOT NULL,
  entry_price NUMERIC(30,12) NOT NULL,
  target_price NUMERIC(30,12) NOT NULL,
  stop_loss_price NUMERIC(30,12) NOT NULL,
  status VARCHAR(24) NOT NULL,
  closed_at TIMESTAMP WITH TIME ZONE,
  close_price NUMERIC(30,12),
  last_checked_price NUMERIC(30,12),
  result_percent DOUBLE PRECISION,
  telegram_message_id BIGINT,
  active_key VARCHAR(300) UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_mix_sim_status_coin ON mix_trade_simulations(status,coin_id);
CREATE INDEX idx_mix_sim_opened ON mix_trade_simulations(opened_at);
CREATE INDEX idx_mix_sim_closed ON mix_trade_simulations(closed_at);

CREATE TABLE telegram_daily_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_date DATE NOT NULL UNIQUE,
  period_start TIMESTAMP WITH TIME ZONE NOT NULL,
  period_end TIMESTAMP WITH TIME ZONE NOT NULL,
  generated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  telegram_message_id BIGINT,
  status VARCHAR(16) NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  error VARCHAR(500),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
