package io.tornado.api;
import io.tornado.persistence.*;import io.tornado.reporting.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.math.*;import java.time.*;import java.util.*;
@RestController@RequestMapping("/api")public class MixReportingController{private final BestMethodMixRepository mixes;private final BestMixService bestMixes;private final MixTradeSimulationService simulations;public MixReportingController(BestMethodMixRepository m,BestMixService b,MixTradeSimulationService s){mixes=m;bestMixes=b;simulations=s;}
 @GetMapping("/reports/best-mixes")List<BestMixDto>best(@RequestParam(required=false)String coin,@RequestParam(required=false)Long horizon){return mixes.findBySignalVersionOrderByCoinSymbolAscHorizonSecondsAscMixSizeAscRankAsc(3).stream().filter(x->coin==null||x.getCoin().getSymbol().equalsIgnoreCase(coin)).filter(x->horizon==null||x.getHorizonSeconds()==ReportService.requireSupportedHorizon(horizon)).map(BestMixDto::of).toList();}
 @PostMapping("/reports/best-mixes/rebuild")@ResponseStatus(HttpStatus.ACCEPTED)Map<String,String>rebuild(){bestMixes.rebuildAll();return Map.of("status","rebuilt");}
 @GetMapping("/mix-simulations")List<SimulationDto>simulations(@RequestParam(required=false)MixTradeSimulation.Status status){return simulations.list(status).stream().map(SimulationDto::of).toList();}
 @GetMapping("/mix-simulations/{id}")SimulationDto simulation(@PathVariable long id){return SimulationDto.of(simulations.get(id));}
 public record BestMixDto(long id,String coin,long horizonSeconds,int mixSize,int rank,List<String>strategyCodes,List<Integer>strategyVersions,List<String>methods,long samples,long targetHits,double targetHitRate,long directionalCorrect,double directionalAccuracy,double wilsonScore,double rankingScore,Instant calculatedAt){static BestMixDto of(BestMethodMix x){return new BestMixDto(x.getId(),x.getCoin().getSymbol(),x.getHorizonSeconds(),x.getMixSize(),x.getRank(),x.getStrategyCodes(),x.getStrategyVersions(),x.getMethodNames(),x.getSamples(),x.getTargetHits(),x.getTargetHitRate(),x.getDirectionalCorrect(),x.getDirectionalAccuracy(),x.getWilsonScore(),x.getRankingScore(),x.getCalculatedAt());}}
 public record SimulationDto(long id,String coin,String pair,long horizonSeconds,int mixSize,int mixRank,List<String>methods,Direction direction,int agreementCount,int totalMethods,Instant openedAt,BigDecimal entryPrice,BigDecimal targetPrice,BigDecimal stopLossPrice,MixTradeSimulation.Status status,Instant closedAt,BigDecimal closePrice,BigDecimal lastCheckedPrice,Double resultPercent,Long telegramMessageId){static SimulationDto of(MixTradeSimulation x){return new SimulationDto(x.getId(),x.getCoin().getSymbol(),x.getCoin().getPair(),x.getHorizonSeconds(),x.getMixSize(),x.getMixRank(),x.getMethodNames(),x.getDirection(),x.getAgreementCount(),x.getTotalMethods(),x.getOpenedAt(),x.getEntryPrice(),x.getTargetPrice(),x.getStopLossPrice(),x.getStatus(),x.getClosedAt(),x.getClosePrice(),x.getLastCheckedPrice(),x.getResultPercent(),x.getTelegramMessageId());}}
}
