package io.tornado.api;
import io.tornado.persistence.*;import io.tornado.reporting.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.math.*;import java.time.*;import java.util.*;
@RestController@RequestMapping("/api")public class MixReportingController{private final BestMethodMixRepository mixes;private final BestMixService bestMixes;private final MixTradeSimulationService simulations;private final AppSettingsRepository settings;private final BestMixRankingPolicy rankings;public MixReportingController(BestMethodMixRepository m,BestMixService b,MixTradeSimulationService s,AppSettingsRepository settings,BestMixRankingPolicy rankings){mixes=m;bestMixes=b;simulations=s;this.settings=settings;this.rankings=rankings;}
 @GetMapping("/reports/best-mixes")List<BestMixDto>best(@RequestParam(required=false)String coin,@RequestParam(required=false)Long horizon,@RequestParam(defaultValue="1")int tpLevel){if(tpLevel<1||tpLevel>3)throw new IllegalArgumentException("tpLevel must be 1, 2, or 3");var levels=settings.findById(1).orElseThrow().getTpSlLevels();return mixes.findBySignalVersionAndTpLevelOrderByCoinSymbolAscHorizonSecondsAscMixSizeAscRankAsc(3,tpLevel).stream().filter(x->rankings.isCurrent(x,levels)).filter(x->coin==null||x.getCoin().getSymbol().equalsIgnoreCase(coin)).filter(x->horizon==null||x.getHorizonSeconds()==ReportService.requireSupportedHorizon(horizon)).map(BestMixDto::of).toList();}
 @PostMapping("/reports/best-mixes/rebuild")@ResponseStatus(HttpStatus.ACCEPTED)Map<String,String>rebuild(){bestMixes.rebuildAll();return Map.of("status","rebuilt");}
 @GetMapping("/mix-simulations")List<SimulationDto>simulations(@RequestParam(required=false)MixTradeSimulation.Status status){return simulations.list(status).stream().map(SimulationDto::of).toList();}@GetMapping("/mix-simulations/{id}")SimulationDto simulation(@PathVariable long id){return SimulationDto.of(simulations.get(id));}
 public record BestMixDto(long id,String coin,long horizonSeconds,int tpLevel,BigDecimal targetPercent,int mixSize,int rank,List<String>strategyCodes,List<Integer>strategyVersions,List<String>methods,long samples,long targetHits,double targetHitRate,long directionalCorrect,double directionalAccuracy,double wilsonScore,double rankingScore,Instant calculatedAt){static BestMixDto of(BestMethodMix x){return new BestMixDto(x.getId(),x.getCoin().getSymbol(),x.getHorizonSeconds(),x.getTpLevel(),x.getTargetPercent(),x.getMixSize(),x.getRank(),x.getStrategyCodes(),x.getStrategyVersions(),x.getMethodNames(),x.getSamples(),x.getTargetHits(),x.getTargetHitRate(),x.getDirectionalCorrect(),x.getDirectionalAccuracy(),x.getWilsonScore(),x.getRankingScore(),x.getCalculatedAt());}}
 public record SimulationDto(long id,String coin,String pair,long horizonSeconds,int mixSize,int mixRank,List<String>methods,Direction direction,int agreementCount,int totalMethods,Instant openedAt,BigDecimal entryPrice,BigDecimal targetPrice,BigDecimal stopLossPrice,BigDecimal tp1Percent,BigDecimal tp2Percent,BigDecimal tp3Percent,BigDecimal sl1Percent,BigDecimal sl2Percent,BigDecimal sl3Percent,BigDecimal tp1Price,BigDecimal tp2Price,BigDecimal tp3Price,BigDecimal sl1Price,BigDecimal sl2Price,BigDecimal sl3Price,Instant tp1HitAt,Instant tp2HitAt,Instant tp3HitAt,Instant sl1HitAt,Instant sl2HitAt,Instant sl3HitAt,MixTradeSimulation.Status status,MixTradeSimulation.TradeOutcome tradeOutcome,Instant successAt,Instant closedAt,BigDecimal closePrice,BigDecimal lastCheckedPrice,Double resultPercent,Long telegramMessageId){static SimulationDto of(MixTradeSimulation x){return new SimulationDto(x.getId(),x.getCoin().getSymbol(),x.getCoin().getPair(),x.getHorizonSeconds(),x.getMixSize(),x.getMixRank(),x.getMethodNames(),x.getDirection(),x.getAgreementCount(),x.getTotalMethods(),x.getOpenedAt(),x.getEntryPrice(),x.getTargetPrice(),x.getStopLossPrice(),x.getTp1Percent(),x.getTp2Percent(),x.getTp3Percent(),x.getSl1Percent(),x.getSl2Percent(),x.getSl3Percent(),x.getTp1Price(),x.getTp2Price(),x.getTp3Price(),x.getSl1Price(),x.getSl2Price(),x.getSl3Price(),x.getTp1HitAt(),x.getTp2HitAt(),x.getTp3HitAt(),x.getSl1HitAt(),x.getSl2HitAt(),x.getSl3HitAt(),x.getStatus(),x.getTradeOutcome(),x.getSuccessAt(),x.getClosedAt(),x.getClosePrice(),x.getLastCheckedPrice(),x.getResultPercent(),x.getTelegramMessageId());}}
}
