package io.tornado.api;

import io.tornado.datafetch.LivePriceStream;
import io.tornado.datafetch.BinanceMarketDataClient;
import io.tornado.persistence.*;
import io.tornado.scheduler.PredictionService;
import io.tornado.reporting.MixSignalSettingsService;
import io.tornado.strategies.StrategyDefinition;
import jakarta.validation.Valid; import jakarta.validation.constraints.*;
import org.springframework.format.annotation.DateTimeFormat; import org.springframework.http.*; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*;
import reactor.core.publisher.Flux;
import java.time.*; import java.util.*;

@RestController @RequestMapping("/api")
public class TornadoController {
 private final CoinRepository coins; private final PredictionRepository predictions; private final AnalysisRunRepository runs; private final AppSettingsRepository settings; private final PredictionService service; private final LivePriceStream prices; private final BinanceMarketDataClient market; private final ReportService reports; private final ExcelReportService excel;private final io.tornado.config.TelegramProperties telegram;private final MixSignalSettingsService mixSignalSettingsService;
 public TornadoController(CoinRepository c,PredictionRepository p,AnalysisRunRepository r,AppSettingsRepository a,PredictionService s,LivePriceStream l,BinanceMarketDataClient m,ReportService reports,ExcelReportService excel,io.tornado.config.TelegramProperties telegram,MixSignalSettingsService mixSignalSettings){coins=c;predictions=p;runs=r;settings=a;service=s;prices=l;market=m;this.reports=reports;this.excel=excel;this.telegram=telegram;this.mixSignalSettingsService=mixSignalSettings;}
 @GetMapping("/coins") List<Coin> coins(){return coins.findAllByActiveTrueOrderBySymbol();}
 @PostMapping("/coins") ResponseEntity<Coin> add(@Valid @RequestBody CoinRequest r){String symbol=r.symbol().toUpperCase(Locale.ROOT);String pair=r.pair().toUpperCase(Locale.ROOT);return ResponseEntity.status(201).body(coins.findBySymbolIgnoreCase(symbol).filter(Coin::isActive).orElseGet(()->coins.save(new Coin(symbol,pair))));}
 @DeleteMapping("/coins/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) @Transactional void remove(@PathVariable long id){coins.findById(id).orElseThrow().deactivate();}
 @GetMapping("/methods") List<MethodDto> methods(){return Arrays.stream(StrategyDefinition.values()).map(x->new MethodDto(x.name(),x.label())).toList();}
 @PostMapping("/run-now") PredictionService.RunResult run(@Valid @RequestBody RunRequest r){return service.snapshot(r.name());}
 @GetMapping("/runs") List<RunSummary> runs(){var recent=runs.findTop100ByOrderByCreatedAtDesc();if(recent.isEmpty())return List.of();var stats=predictions.summarizeRuns(recent.stream().map(AnalysisRun::getId).toList()).stream().collect(java.util.stream.Collectors.toMap(PredictionRepository.RunStats::getRunId,x->x));return recent.stream().map(r->summary(r,stats.get(r.getId()))).toList();}
 @GetMapping("/runs/{id}") RunReport run(@PathVariable long id){var r=runs.findById(id).orElseThrow();var ps=predictions.findByAnalysisRunIdOrderByCoinSymbolAscMethodNameAsc(id);return new RunReport(summary(r,stats(ps)),ps);}
 @GetMapping("/method-report") MethodReport method(@RequestParam String method,@RequestParam(defaultValue="3600")long horizon,@RequestParam(defaultValue="3")int signalVersion){ReportService.requireSupportedHorizon(horizon);ReportService.requireSignalVersion(signalVersion);var ps=predictions.findByMethodNameAndSignalVersionAndHorizonSecondsOrderByPredictedAtDesc(method,signalVersion,horizon);long graded=ps.stream().filter(p->p.getOutcome()==Outcome.CORRECT||p.getOutcome()==Outcome.INCORRECT).count(),targetCorrect=ps.stream().filter(p->p.getOutcome()==Outcome.CORRECT).count(),directionalCorrect=ps.stream().filter(this::directionCorrect).count();return new MethodReport(method,ps.size(),graded,targetCorrect,graded==0?0:targetCorrect*100.0/graded,directionalCorrect,graded==0?0:directionalCorrect*100.0/graded,ps);}
 @GetMapping("/prices") Map<String,LivePriceStream.PriceTick> currentPrices(){return prices.latest();}
 @GetMapping("/chart/{pair}") List<BinanceMarketDataClient.Candle> chart(@PathVariable String pair,@RequestParam(defaultValue="15m")String interval,@RequestParam(defaultValue="120")int limit){return market.chart(pair.toUpperCase(Locale.ROOT),interval,limit);}
 @GetMapping("/reports/coins") List<ReportService.CoinReport> coinReports(@RequestParam(defaultValue="3")@Min(1)int minSamples,@RequestParam(defaultValue="3600")long horizon,@RequestParam(defaultValue="3")int signalVersion,@RequestParam(defaultValue="1")int tpLevel){return reports.coinReports(minSamples,horizon,signalVersion,tpLevel);}
 @GetMapping("/reports/mixes") List<ReportService.MixAccuracy> mixReports(@RequestParam(defaultValue="3")@Min(1)int minSamples,@RequestParam(defaultValue="3")int size,@RequestParam(defaultValue="3600")long horizon,@RequestParam(defaultValue="3")int signalVersion,@RequestParam(defaultValue="1")int tpLevel){return reports.mixReports(minSamples,size,horizon,signalVersion,tpLevel);}
 @GetMapping("/reports/coin-mixes") List<ReportService.CoinMixReport> coinMixReports(@RequestParam(defaultValue="3")@Min(1)int minSamples,@RequestParam(defaultValue="3")int size,@RequestParam(defaultValue="3600")long horizon,@RequestParam(defaultValue="3")int signalVersion,@RequestParam(defaultValue="1")int tpLevel){return reports.coinMixReports(minSamples,size,horizon,signalVersion,tpLevel);}
 @GetMapping("/reports/super") ReportService.SuperReport superReport(@RequestParam(defaultValue="5")@Min(1)int minSamples,@RequestParam(defaultValue="3600")long horizon,@RequestParam(defaultValue="3")int signalVersion,@RequestParam(defaultValue="1")int tpLevel){return reports.superReport(minSamples,horizon,signalVersion,tpLevel);}
 @GetMapping(value="/reports/super/excel",produces="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet") ResponseEntity<byte[]> superExcel(@RequestParam(defaultValue="3")int signalVersion,@RequestParam(defaultValue="1")int tpLevel){return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=super-analysis-tp"+tpLevel+".xlsx").body(excel.superAnalysis(signalVersion,tpLevel));}
 @PostMapping("/reports/money") ReportService.MoneyReport moneyReport(@RequestBody ReportService.MoneyRequest request,@RequestParam(defaultValue="3")int signalVersion,@RequestParam(defaultValue="1")int tpLevel){return reports.moneyReport(request,signalVersion,tpLevel);}
 @GetMapping("/predictions") List<Prediction> history(@RequestParam(defaultValue="3")int signalVersion,@RequestParam(required=false)String coin,@RequestParam(required=false)String method,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME)Instant from,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME)Instant to){ReportService.requireSignalVersion(signalVersion);return predictions.searchCurrent(signalVersion,blank(coin),blank(method),from==null?Instant.now().minus(Duration.ofDays(30)):from,to==null?Instant.now():to);}
 @GetMapping("/predictions/horizon-aware") List<Prediction> horizonAwareHistory(@RequestParam(required=false)String coin,@RequestParam(required=false)String method,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME)Instant from,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME)Instant to){return predictions.searchCurrent(3,blank(coin),blank(method),from==null?Instant.now().minus(Duration.ofDays(30)):from,to==null?Instant.now():to);}
 @GetMapping("/predictions/history") List<Prediction> allHistory(@RequestParam(required=false)String coin,@RequestParam(required=false)String method,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME)Instant from,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME)Instant to){return predictions.searchAll(blank(coin),blank(method),from==null?Instant.now().minus(Duration.ofDays(30)):from,to==null?Instant.now():to);}
 @GetMapping("/leaderboard") List<LeaderRow> board(@RequestParam(required=false)String coin,@RequestParam(defaultValue="7d")String window,@RequestParam(defaultValue="3600")long horizon,@RequestParam(defaultValue="3")int signalVersion){ReportService.requireSupportedHorizon(horizon);ReportService.requireSignalVersion(signalVersion);Instant from=Instant.now().minus(parseWindow(window));return predictions.leaderboard(blank(coin),from,horizon,signalVersion).stream().map(r->{long total=((Number)r[1]).longValue(),targetCorrect=((Number)r[2]).longValue(),directionalCorrect=((Number)r[3]).longValue();return new LeaderRow((String)r[0],total,targetCorrect,total==0?0:targetCorrect*100.0/total,directionalCorrect,total==0?0:directionalCorrect*100.0/total);}).sorted(Comparator.comparingDouble(LeaderRow::targetHitRate).reversed()).toList();}
 @GetMapping(value="/prices/stream",produces=MediaType.TEXT_EVENT_STREAM_VALUE) Flux<LivePriceStream.PriceTick> live(){return prices.flux();}
 @GetMapping("/settings") AppSettings setting(){return settings.findById(1).orElseThrow();}
 @PutMapping("/settings") @Transactional AppSettings setting(@Valid @RequestBody SettingsRequest r){var s=settings.findById(1).orElseThrow();s.update(r.snapshotIntervalSeconds(),r.gradingHorizonSeconds());return s;}
 @GetMapping("/settings/notifications") TelegramSettings telegramSettings(){var s=settings.findById(1).orElseThrow();return new TelegramSettings(s.isTelegramNotificationsEnabled(),telegram.configured(),telegram.chatId());}
 @PutMapping("/settings/notifications") @Transactional TelegramSettings telegramSettings(@RequestBody TelegramSettingsRequest request){var s=settings.findById(1).orElseThrow();s.updateTelegram(request.enabled());return new TelegramSettings(s.isTelegramNotificationsEnabled(),telegram.configured(),telegram.chatId());}
 @GetMapping("/settings/mix-signals") MixSignalSettings mixSignalSettings(){return MixSignalSettings.of(settings.findById(1).orElseThrow());}
 @PutMapping("/settings/mix-signals") MixSignalSettings mixSignalSettings(@Valid @RequestBody MixSignalSettingsRequest request){var levels=new TpSlLevels(request.mixTradeTp1Percent(),request.mixTradeTp2Percent(),request.mixTradeTp3Percent(),request.mixTradeSl1Percent(),request.mixTradeSl2Percent(),request.mixTradeSl3Percent());return MixSignalSettings.of(mixSignalSettingsService.update(request.minimumMixSimulationTrades(),levels,request.minimumNotificationWinRatePercent(),request.telegramDailyReportEnabled()));}
 @GetMapping("/settings/profile-selection") ProfileSelectionSettings profileSelectionSettings(){return ProfileSelectionSettings.of(settings.findById(1).orElseThrow());}
 @PutMapping("/settings/profile-selection") @Transactional ProfileSelectionSettings profileSelectionSettings(@Valid @RequestBody ProfileSelectionSettingsRequest request){var s=settings.findById(1).orElseThrow();s.updateProfileSelection(request.minimumConfigurationSamples(),request.coinProfileMinimumSamples(),request.profileReplacementMinimumImprovementPercent(),request.profileResearchRoundTripCostPercent(),request.profileRefreshIntervalHours(),request.automaticProfileResearchEnabled());return ProfileSelectionSettings.of(s);}
 private String blank(String s){return s==null||s.isBlank()?null:s.toUpperCase(Locale.ROOT);}
 private boolean directionCorrect(Prediction p){if((p.getOutcome()!=Outcome.CORRECT&&p.getOutcome()!=Outcome.INCORRECT)||p.getPriceAtGrading()==null)return false;int c=p.getPriceAtGrading().compareTo(p.getPriceAtPrediction());return p.getPredictedDirection()==Direction.UP?c>0:c<0;}
 private Duration parseWindow(String w){long n=Long.parseLong(w.substring(0,w.length()-1));return switch(w.charAt(w.length()-1)){case'h'->Duration.ofHours(n);case'd'->Duration.ofDays(n);case'w'->Duration.ofDays(n*7);default->throw new IllegalArgumentException("window must end in h, d, or w");};}
 private PredictionRepository.RunStats stats(List<Prediction> ps){long pending=ps.stream().filter(p->p.getOutcome()==Outcome.PENDING).count(),ungradable=ps.stream().filter(p->p.getOutcome()==Outcome.UNGRADABLE).count(),correct=ps.stream().filter(p->p.getOutcome()==Outcome.CORRECT).count(),graded=ps.stream().filter(p->p.getOutcome()==Outcome.CORRECT||p.getOutcome()==Outcome.INCORRECT).count(),directional=ps.stream().filter(this::directionCorrect).count();return new RunStatsValue(ps.isEmpty()?null:ps.getFirst().getAnalysisRun().getId(),ps.size(),pending,ungradable,correct,graded,directional);}
 private RunSummary summary(AnalysisRun r,PredictionRepository.RunStats s){long total=s==null?0:s.getPredictions(),pending=s==null?0:s.getPending(),ungradable=s==null?0:s.getUngradable(),correct=s==null?0:s.getTargetCorrect(),graded=s==null?0:s.getGraded(),directional=s==null?0:s.getDirectionalCorrect();return new RunSummary(r.getId(),r.getName(),r.getCreatedAt(),r.getHorizonSeconds(),r.getStatus().name(),total,pending,ungradable,correct,graded==0?0:correct*100.0/graded,directional,graded==0?0:directional*100.0/graded,r.getErrorCount());}
 private record RunStatsValue(Long runId,long predictions,long pending,long ungradable,long targetCorrect,long graded,long directionalCorrect) implements PredictionRepository.RunStats{public Long getRunId(){return runId;}public long getPredictions(){return predictions;}public long getPending(){return pending;}public long getUngradable(){return ungradable;}public long getTargetCorrect(){return targetCorrect;}public long getGraded(){return graded;}public long getDirectionalCorrect(){return directionalCorrect;}}
 public record CoinRequest(@NotBlank @Pattern(regexp="[A-Za-z0-9]{2,20}")String symbol,@NotBlank @Pattern(regexp="[A-Za-z0-9]{4,30}")String pair){}
 public record SettingsRequest(@Min(60)long snapshotIntervalSeconds,@Min(60)long gradingHorizonSeconds){}
 public record TelegramSettingsRequest(boolean enabled){}
 public record TelegramSettings(boolean enabled,boolean environmentConfigured,String chatId){}
 public record MixSignalSettingsRequest(@Min(1)@Max(100000)int minimumMixSimulationTrades,@com.fasterxml.jackson.annotation.JsonAlias("takeProfit1Percent")@DecimalMin("0.01")@DecimalMax("20")java.math.BigDecimal mixTradeTp1Percent,@com.fasterxml.jackson.annotation.JsonAlias("takeProfit2Percent")@DecimalMin("0.01")@DecimalMax("20")java.math.BigDecimal mixTradeTp2Percent,@com.fasterxml.jackson.annotation.JsonAlias("takeProfit3Percent")@DecimalMin("0.01")@DecimalMax("20")java.math.BigDecimal mixTradeTp3Percent,@com.fasterxml.jackson.annotation.JsonAlias("stopLoss1Percent")@DecimalMin("0.01")@DecimalMax("20")java.math.BigDecimal mixTradeSl1Percent,@com.fasterxml.jackson.annotation.JsonAlias("stopLoss2Percent")@DecimalMin("0.01")@DecimalMax("20")java.math.BigDecimal mixTradeSl2Percent,@com.fasterxml.jackson.annotation.JsonAlias("stopLoss3Percent")@DecimalMin("0.01")@DecimalMax("20")java.math.BigDecimal mixTradeSl3Percent,@DecimalMin("0")@DecimalMax("100")java.math.BigDecimal minimumNotificationWinRatePercent,boolean telegramDailyReportEnabled){}
 public record MixSignalSettings(int minimumMixSimulationTrades,java.math.BigDecimal mixTradeTp1Percent,java.math.BigDecimal mixTradeTp2Percent,java.math.BigDecimal mixTradeTp3Percent,java.math.BigDecimal mixTradeSl1Percent,java.math.BigDecimal mixTradeSl2Percent,java.math.BigDecimal mixTradeSl3Percent,java.math.BigDecimal minimumNotificationWinRatePercent,boolean telegramDailyReportEnabled){static MixSignalSettings of(AppSettings s){return new MixSignalSettings(s.getMinimumMixSimulationTrades(),s.getTakeProfit1Percent(),s.getTakeProfit2Percent(),s.getTakeProfit3Percent(),s.getStopLoss1Percent(),s.getStopLoss2Percent(),s.getStopLoss3Percent(),s.getMinimumNotificationWinRatePercent(),s.isTelegramDailyReportEnabled());}}
 public record ProfileSelectionSettingsRequest(@Min(30)@Max(100000)int minimumConfigurationSamples,@Min(30)@Max(100000)int coinProfileMinimumSamples,@DecimalMin("0")@DecimalMax("50")java.math.BigDecimal profileReplacementMinimumImprovementPercent,@DecimalMin("0")@DecimalMax("10")java.math.BigDecimal profileResearchRoundTripCostPercent,@Min(1)@Max(8760)int profileRefreshIntervalHours,boolean automaticProfileResearchEnabled){}
 public record ProfileSelectionSettings(int minimumConfigurationSamples,int coinProfileMinimumSamples,java.math.BigDecimal profileReplacementMinimumImprovementPercent,java.math.BigDecimal profileResearchRoundTripCostPercent,int profileRefreshIntervalHours,boolean automaticProfileResearchEnabled){static ProfileSelectionSettings of(AppSettings s){return new ProfileSelectionSettings(s.getMinimumConfigurationSamples(),s.getCoinProfileMinimumSamples(),s.getProfileReplacementMinimumImprovementPercent(),s.getProfileResearchRoundTripCostPercent(),s.getProfileRefreshIntervalHours(),s.isAutomaticProfileResearchEnabled());}}
 public record RunRequest(@NotBlank @Size(max=120)String name,Integer checkerMinutes){}
 public record RunSummary(long id,String name,Instant createdAt,long horizonSeconds,String status,long predictions,long pending,long ungradable,long targetCorrect,double targetHitRate,long directionalCorrect,double directionalAccuracy,int errors){}
 public record RunReport(RunSummary summary,List<Prediction> predictions){}
 public record MethodReport(String method,long total,long graded,long targetCorrect,double targetHitRate,long directionalCorrect,double directionalAccuracy,List<Prediction> predictions){}
 public record MethodDto(String id,String name){} public record LeaderRow(String method,long total,long targetCorrect,double targetHitRate,long directionalCorrect,double directionalAccuracy){}
}
