package io.tornado.reporting;
import io.tornado.datafetch.BinanceMarketDataClient;import io.tornado.notification.*;import io.tornado.persistence.*;import org.junit.jupiter.api.Test;import org.mockito.ArgumentCaptor;import org.springframework.test.util.ReflectionTestUtils;import java.math.*;import java.time.*;import java.util.*;import static org.assertj.core.api.Assertions.assertThat;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
class MixTradeSimulationServiceTest{
 @Test void qualifyingConsensusCreatesOneSimulationWithPersistedLadderAndTelegramId(){Fixture f=new Fixture();when(f.simulations.existsByActiveKey(anyString())).thenReturn(false);when(f.simulations.saveAndFlush(any())).thenAnswer(i->{MixTradeSimulation s=i.getArgument(0);ReflectionTestUtils.setField(s,"id",99L);return s;});when(f.telegram.send(anyString())).thenReturn(sent());f.service.detect(f.coin,f.predictions(),Instant.EPOCH,new BigDecimal("100"));ArgumentCaptor<MixTradeSimulation>capture=ArgumentCaptor.forClass(MixTradeSimulation.class);verify(f.simulations).saveAndFlush(capture.capture());assertThat(capture.getValue().getTelegramMessageId()).isEqualTo(42);assertThat(capture.getValue().getTp3Price()).isEqualByComparingTo("101");verify(f.telegram).send(messageContaining("TP1","TP2","TP3","SL1","SL2","SL3"));}
 @Test void duplicateActiveKeySuppressesSimulationAndNotification(){Fixture f=new Fixture();when(f.simulations.existsByActiveKey(anyString())).thenReturn(true);f.service.detect(f.coin,f.predictions(),Instant.EPOCH,new BigDecimal("100"));verify(f.simulations,never()).saveAndFlush(any());verifyNoInteractions(f.telegram);}
 @Test void oneTickCrossingAllTargetsProducesOneTerminalEdit(){Fixture f=new Fixture();MixTradeSimulation s=f.simulation(Direction.UP);when(f.simulations.lockOpenByPair("BTCUSDT")).thenReturn(List.of(s));when(f.telegram.edit(eq(42L),anyString())).thenReturn(sent());f.service.observe("BTCUSDT",new BigDecimal("101.2"),Instant.EPOCH.plusSeconds(60));assertThat(s.getStatus()).isEqualTo(MixTradeSimulation.Status.TP3_HIT);assertThat(s.getTp1HitAt()).isEqualTo(s.getTp3HitAt());verify(f.telegram,times(1)).edit(eq(42L),messageContaining("TP1 TOUCHED","TP2 TOUCHED","TP3 TOUCHED","TP3 HIT"));verify(f.telegram,never()).send(anyString());}
 @Test void stopTerminalEditFallsBackWithoutLosingState(){Fixture f=new Fixture();MixTradeSimulation s=f.simulation(Direction.DOWN);when(f.simulations.lockOpenByPair("BTCUSDT")).thenReturn(List.of(s));when(f.telegram.edit(eq(42L),anyString())).thenReturn(new TelegramNotificationService.DeliveryResult(TelegramNotificationService.DeliveryResult.Status.FAILED,null,"edit failed"));f.service.observe("BTCUSDT",new BigDecimal("101.2"),Instant.EPOCH.plusSeconds(60));assertThat(s.getStatus()).isEqualTo(MixTradeSimulation.Status.SL3_HIT);verify(f.telegram).edit(eq(42L),contains("SL3 HIT"));verify(f.telegram).send(contains("SL3 HIT"));}
 @Test void recoveryPreservesOrderedMixedTouchesAndCoalescesEdit(){Fixture f=new Fixture();MixTradeSimulation s=f.simulation(Direction.UP);when(f.simulations.lockOpenByPair("BTCUSDT")).thenReturn(List.of(s));when(f.market.historicalTrades(eq("BTCUSDT"),eq(Instant.EPOCH),eq(Instant.EPOCH.plusSeconds(30)))).thenReturn(List.of(new BinanceMarketDataClient.AggregateTrade(1,new BigDecimal("99.4"),Instant.EPOCH.plusSeconds(10)),new BinanceMarketDataClient.AggregateTrade(2,new BigDecimal("100.6"),Instant.EPOCH.plusSeconds(20))));when(f.telegram.edit(eq(42L),anyString())).thenReturn(sent());f.service.recover("BTCUSDT",Instant.EPOCH.plusSeconds(30));assertThat(s.getStatus()).isEqualTo(MixTradeSimulation.Status.OPEN);assertThat(s.getSl1HitAt()).isEqualTo(Instant.EPOCH.plusSeconds(10));assertThat(s.getTp1HitAt()).isEqualTo(Instant.EPOCH.plusSeconds(20));verify(f.telegram,times(1)).edit(eq(42L),messageContaining("SL1 TOUCHED","SL2 TOUCHED","TP1 TOUCHED","TP2 TOUCHED"));}
 private String messageContaining(String...parts){return argThat(x->Arrays.stream(parts).allMatch(x::contains));}private TelegramNotificationService.DeliveryResult sent(){return new TelegramNotificationService.DeliveryResult(TelegramNotificationService.DeliveryResult.Status.SENT,42L,null);}
 static class Fixture{final Coin coin=new Coin("BTC","BTCUSDT");final BestMethodMixRepository mixes=mock(BestMethodMixRepository.class);final MixTradeSimulationRepository simulations=mock(MixTradeSimulationRepository.class);final AppSettingsRepository settings=mock(AppSettingsRepository.class);final TelegramNotificationService telegram=mock(TelegramNotificationService.class);final BinanceMarketDataClient market=mock(BinanceMarketDataClient.class);final BestMethodMix mix;final MixTradeSimulationService service;Fixture(){ReflectionTestUtils.setField(coin,"id",1L);mix=new BestMethodMix(coin,900,3,1,List.of("A","B","C"),List.of(1,1,1),List.of("A","B","C"),50,30,35,.5);ReflectionTestUtils.setField(mix,"id",2L);when(mixes.findByCoinIdAndHorizonSecondsAndSignalVersionAndTpLevelOrderByMixSizeAscRankAsc(1,900,3,1)).thenReturn(List.of(mix));AppSettings config=new AppSettings(900,900);config.updateTelegram(true);when(settings.findById(1)).thenReturn(Optional.of(config));service=new MixTradeSimulationService(mixes,simulations,settings,telegram,new TelegramMessageFormatter(),market);}MixTradeSimulation simulation(Direction direction){MixTradeSimulation s=new MixTradeSimulation(coin,mix,direction,2,new BigDecimal("100"),TpSlLevels.defaults(),Instant.EPOCH);ReflectionTestUtils.setField(s,"id",99L);s.telegramMessage(42L);return s;}List<Prediction>predictions(){return List.of(prediction("A",Direction.UP),prediction("B",Direction.UP),prediction("C",Direction.DOWN));}Prediction prediction(String code,Direction direction){return new Prediction(null,coin,code,1,code,Instant.EPOCH,new BigDecimal("100"),Instant.EPOCH,new BigDecimal("100"),direction,Duration.ofMinutes(15),"5m");}}
}
